column_names = [
    'Enroll Number',
    'Name',
    'Faculty Code(3 Digit Code eg:"AGP")',
    'Designation',
    'Gender',
    'Date of Birth [Official]',
    'Date of Birth [Actual]',
    'Qualifications',
    'Additional Eligibility/Qualifications',
    'Department',
    'KTU-ID',
    'Google Scholar ID',
    'ORCID iD',
    'Year of obtaining Ph. D.(if Applicable)',
    'Year of recognition as Ph.D. guide(if Applicable)',
    'Ph.D Guideship',
    'Religion',
    'Caste',
    'Category',
    'Communication Address',
    'Permanent Address',
    'Blood Group',
    'Physically Handicapped',
    'Aadhar No.',
    'Experience',
    'Area of Interest',
    'Memberships, if any',
    'Email Address(RAJAGIRITECH.EDU.IN)',
    'Email Address(GMAIL)',
    'Mobile Number',
    'Whatsapp Number',
    'Facebook Profile[link]',
    'Linkedin Profile[link]',
    'Instagram Profile[link]',
    'Twitter Profile[link]',
    'Threads Profile[link]',
    'Personal Website',
    'Landline',
    'Emergency Contact Number',
    'Staff/Lab Phone Extn. No',
    'Staff/Lab Room No',
    'Staff/Lab Room Name',
    'Primary Vehicle No',
    'Secondary Vehicle No',
    'Third Vehicle No',
    'Rajagiri Valley South Indian Bank A/C No',
    'College Laptop Number(if Any)',
    'College Laptop Make(if Any)',
    'Laptop Issue Date',
    'Active',
    'Date of Join',
    'Date of Joining in Teaching Profession',
    'No of Years Spent Other than Teaching Jobs',
    'Last Promotion Date'
]